### ISSUE TITLE
Per project haxe version

### ISSUE THREAD

**Issue by enderpuff** [kLabz/haxe-manager#5]
Not sure if this is possible, but i was wondering if there would be a way to set a haxe version for a specific project (Example, i have some code that works on an older version of haxe but everything else i want to use latest)

**Comment by kLabz** [comment]
I'm still not sure I want to go the haxe shim route and make it automatic (especially since I usually _don't_ want that behavior myself), but I added `hx rc` command to apply `.haxerc` manually:

https://asciinema.org/a/zEEbWpl24fJhD6CtAub7sTt9t 

Closing this because the automatic part is not planned atm
